### ISSUE TITLE
[Feature request] MP3 support

### ISSUE THREAD

**Issue by orzech1080** [sukumo28/wav-preview#6]
The plugin handles MP3 files out of the box, but the playback is slowed down for some reason (maybe a bitrate issue?). 
I know it's called "wav-preview", but it would be great if it supported other audio file types ;) I couldn't find any VScode extension that does that.

Great job so far!

**Comment by sukumo28** [comment]
There are other PRs that want MP3 support, so I'll try to support it if possible.
However, when playing MP3s, I don't know why the left and right sounds are out of sync or why the song plays slowly.

Possibility ①
There may be a bug in the code in `/media/audioPreview.js`.

Possibility ②
In `wav-preview`, audio is decoded by a library called `audio-decode`.
Previously, when I compared the result of decoding using `AudioContext.decodeAudioData()` of the browser with the result of decoding with `audio-decode`, some values ​​such as `SampleRate` were different.
The browser was playing correctly, so the `audio-decode` decoding result may be incorrect.

In any case, it is difficult to identify the cause because I do not know the MP3 specifications.
There is a charge for viewing MP3 specifications, and even if you can see them, identifying the cause can be a daunting task if the amount is large. 

If you find the cause, please send a Pull Request.

**Comment by sukumo28** [comment]
@orzech1080 
mp3 is supported from v2.0.0!
